theme: jekyll-theme-minimal
title: Unveiling the Hidden Factors Behind an Actor's Success
description: A template website for ADA's project on the CMU Movie Corpus dataset
show_downloads: True

navigation:
  - title: Home
    url: /
  - title: Research Question
    url: /research-question
  - title: Regression Analysis
    url: /regression-analysis.md
  - title: Clustering
    url: /clustering.md
  - title: Network
    url: /network.md
