theme: jekyll-theme-minimal
title: Unveiling the Hidden Factors Behind an Actor's Success
description: by ArabsDataScientists
show_downloads: True

navigation:
  - title: Home
    url: "#home"
  - title: Research Question
    url: "#research-question"
  - title: Regression Analysis
    url: "#regression-analysis"
  - title: Clustering
    url: "#clustering"
  - title: Network
    url: "#network"
